#!/usr/bin/env python3

from phatty.editor import Editor
import phatty.utils
import signal
import setproctitle


def quit(signum, frame):
    editor.quit()


signal.signal(signal.SIGINT, quit)

setproctitle.setproctitle(phatty.utils.APP_NAME)
editor = Editor()
editor.main()
